server.port: 6260

spring:
  codec:
    max-in-memory-size: 10MB
  application:
    name: monsil-server

  r2dbc:
    url: r2dbc:mariadb://34.28.163.85:3306/monsil
    username: zxcyui6181
    password: ghkdals

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
